blank_issues_enabled: true
contact_links:
  - name: LocalStack Documentation
    url: https://localstack.cloud/docs/getting-started/overview/
    about: The LocalStack documentation may answer your questions!
  - name: LocalStack Community Support (Slack)
    url: https://localstack-community.slack.com
    about: Please ask and answer questions here.
